package data_mahasiswa;

import javax.swing.table.*;
import java.sql.*;
import java.util.Date;
import static data_mahasiswa.Koneksi.*;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Marcelius Tri Alvino
 */
public class f_Data_Mahasiswa extends javax.swing.JFrame {
    private DefaultTableModel tb;
    private static String no;
    public f_Data_Mahasiswa() {
        initComponents();
        this.setLocationRelativeTo(null);
                
        tb = new DefaultTableModel(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tabel.setModel(tb);
        tb.addColumn("No");
        tb.addColumn("NIM");
        tb.addColumn("Nama");
        tb.addColumn("Tempat Lahir");
        tb.addColumn("Tanggal Lahir");
        tb.addColumn("Prodi");
        tb.addColumn("Asal Sekolah");
        tb.addColumn("Alamat");
        
        loadData();
        txtNIM.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNIM = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtTempat = new javax.swing.JTextField();
        txtProdi = new javax.swing.JTextField();
        txtAsal = new javax.swing.JTextField();
        dtTanggal = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        btnClear = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DATA MAHASISWA");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("POLITEKNIK LAMANDAU");

        jLabel3.setText("NIM");

        jLabel4.setText("NAMA");

        jLabel5.setText("PRODI");

        jLabel6.setText("TEMPAT LAHIR");

        jLabel7.setText("TANGGAL LAHIR");

        jLabel8.setText("ASAL SEKOLAH");

        jLabel9.setText("ALAMAT");

        txtNIM.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNIMKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNIMKeyTyped(evt);
            }
        });

        txtNama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNamaKeyPressed(evt);
            }
        });

        jLabel10.setText(":");

        jLabel12.setText(":");

        jLabel13.setText(":");

        jLabel11.setText(":");

        jLabel14.setText(":");

        jLabel15.setText(":");

        jLabel16.setText(":");

        jLabel17.setText(":");

        jLabel18.setText(":");

        txtTempat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTempatKeyPressed(evt);
            }
        });

        txtProdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtProdiKeyPressed(evt);
            }
        });

        txtAsal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAsalKeyPressed(evt);
            }
        });

        dtTanggal.setDateFormatString("dd MMMMMMMMMM yyyy");
        dtTanggal.setOpaque(false);
        dtTanggal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dtTanggalKeyPressed(evt);
            }
        });

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        txtAlamat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtAlamatKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txtAlamat);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        tabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tabel);

        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        btnClear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnClearKeyPressed(evt);
            }
        });

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        btnEdit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnEditKeyPressed(evt);
            }
        });

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        btnSimpan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSimpanKeyPressed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        btnHapus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnHapusKeyPressed(evt);
            }
        });

        jLabel19.setText("By. Pembuat: 202287013 - MARCELIUS TRI ALVINO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel3))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel7)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNIM)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtNama)
                                    .addComponent(txtTempat)
                                    .addComponent(txtProdi)
                                    .addComponent(txtAsal)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(272, 272, 272))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel12)
                    .addContainerGap(620, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(194, 194, 194)
                    .addComponent(jLabel13)
                    .addContainerGap(610, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNIM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel15)
                            .addComponent(txtTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7)))
                    .addComponent(dtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel16)
                    .addComponent(txtProdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel17)
                    .addComponent(txtAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jLabel18))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(jLabel12)
                    .addContainerGap(529, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(112, 112, 112)
                    .addComponent(jLabel13)
                    .addContainerGap(519, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtNIM.setText("");
        txtNama.setText("");
        txtTempat.setText("");
        txtProdi.setText("");
        txtAsal.setText("");
        txtAlamat.setText("");
        dtTanggal.setCalendar(null);
        tabel.clearSelection();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i = tabel.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(null, "Silahkan Pilih Baris Data Terlebih Dahulu");
            return;
        }
        
        int opsi = JOptionPane.showConfirmDialog(null, "Yakin Menghapus Data?", "Hapus Data", JOptionPane.YES_NO_OPTION);
        if(opsi == JOptionPane.YES_OPTION){
            String nim = (String) tb.getValueAt(i, 1);
            try{
                Koneksi.koneksi();
                String sql = "delete from mahasiswa where NIM = '" + nim + "'";
                Statement stm = con.createStatement();
                stm.executeUpdate(sql);
                
                loadData();
                JOptionPane.showMessageDialog(null, "Berhasil Menghapus Data");
                btnClearActionPerformed(null);
                stm.close();
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Gagal Menghapus Data\n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        DefaultTableModel dtm = (DefaultTableModel) tabel.getModel(); 
        int selectedRowIndex = tabel.getSelectedRow();
        String nim = (String) dtm.getValueAt(selectedRowIndex, 1);
        try {
            Koneksi.koneksi();
            String sql= "Select * from mahasiswa where NIM = '"+ nim +"'";
            Statement pst = con.prepareStatement(sql); 
            ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
                no = rs.getString("No");
                RowSelect.set_no(no);
                txtNIM.setText(rs.getString("NIM"));
                txtNama.setText(rs.getString("Nama"));
                txtTempat.setText(rs.getString("Tempat_Lahir"));
                dtTanggal.setDate(rs.getDate("Tanggal_Lahir"));
                txtProdi.setText(rs.getString("Prodi"));
                txtAsal.setText(rs.getString("Asal_Sekolah"));
                txtAlamat.setText(rs.getString("Alamat"));
            }
            con.close();
            pst.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Error\n" + ex.getMessage());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String no = null;
        String nim = txtNIM.getText();
        String nama = txtNama.getText();
        String tempat = txtTempat.getText();
        Date tanggal = dtTanggal.getDate();
        String prodi = txtProdi.getText();
        String asal = txtAsal.getText();
        String alamat = txtAlamat.getText();
        
        if(nim.isEmpty() || nama.isEmpty() || tempat.isEmpty() || tanggal == null || prodi.isEmpty() || asal.isEmpty() || alamat.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Lengkap\nSilahkan Isi Data Secara Lengkap");
        }else{
            int opsi = JOptionPane.showConfirmDialog(null, "Yakin Menyimpan Data?", "Simpan Data", JOptionPane.YES_NO_OPTION);
            if(opsi == JOptionPane.YES_OPTION){
                try{
                    Koneksi.koneksi();
                    String sql = "insert into mahasiswa values (?, ?, ?, ?, ?, ?, ?, ?)";
                    PreparedStatement pst = con.prepareStatement(sql);
                    
                    pst.setString(1, no);
                    pst.setString(2, nim);
                    pst.setString(3, nama);
                    pst.setString(4, tempat);
                    pst.setDate(5, new java.sql.Date(tanggal.getTime()));
                    pst.setString(6, prodi);
                    pst.setString(7, asal);
                    pst.setString(8, alamat);
                    
                    pst.executeUpdate();
                    
                    loadData();
                    JOptionPane.showMessageDialog(null, "Berhasil Menyimpan Data");
                    pst.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data\n" + e.getMessage());
                    //System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int i = tabel.getSelectedRow();
        if(i == -1){
            JOptionPane.showMessageDialog(null, "Pilih Baris Data Terlebih Dahulu");
            return;
        }
        
        no = RowSelect.get_no();
        String nim = txtNIM.getText();
        String nama = txtNama.getText();
        String tempat = txtTempat.getText();
        Date tanggal = dtTanggal.getDate();
        String prodi = txtProdi.getText();
        String asal = txtAsal.getText();
        String alamat = txtAlamat.getText();
        
        if(nim.isEmpty() || nama.isEmpty() || tempat.isEmpty() || tanggal == null || prodi.isEmpty() || asal.isEmpty() || alamat.isEmpty()){
            JOptionPane.showMessageDialog(null, "Data Tidak Lengkap\nSilahkan Isi Data Secara Lengkap");
        }else{
            int opsi = JOptionPane.showConfirmDialog(null, "Yakin Mengedit Data?", "Edit Data", JOptionPane.YES_NO_OPTION);
            if(opsi == JOptionPane.YES_OPTION){
                try{
                    Koneksi.koneksi();
                    String sql = "update mahasiswa set NIM = ?, Nama = ?, Tempat_Lahir = ?, Tanggal_Lahir = ?, Prodi = ?, Asal_Sekolah = ?, Alamat = ? where no = ?";
                    PreparedStatement pst = con.prepareStatement(sql);
                    
                    pst.setString(1, nim);
                    pst.setString(2, nama);
                    pst.setString(3, tempat);
                    pst.setDate(4, new java.sql.Date (tanggal.getTime()));
                    pst.setString(5, prodi);
                    pst.setString(6, asal);
                    pst.setString(7, alamat);
                    pst.setString(8, no);
                    
                    pst.executeUpdate();
                    
                    loadData();
                    isi();
                    JOptionPane.showMessageDialog(null, "Berhasil Mengedit Data");
                    pst.close();
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Gagal Menyimpan Data\n" + e.getMessage());
                    //System.out.println(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtNIMKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIMKeyTyped
        String nim = txtNIM.getText();
        int digit = nim.length();
        char c = evt.getKeyChar();

        if(!Character.isDigit(c) || digit > 8){
            evt.consume();
        }
    }//GEN-LAST:event_txtNIMKeyTyped

    private void txtNIMKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNIMKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            txtNama.requestFocus();
        }
    }//GEN-LAST:event_txtNIMKeyPressed

    private void txtNamaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtNIM.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            txtTempat.requestFocus();
        }
    }//GEN-LAST:event_txtNamaKeyPressed

    private void txtTempatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTempatKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtNama.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            dtTanggal.requestFocus();
        }
    }//GEN-LAST:event_txtTempatKeyPressed

    private void dtTanggalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtTanggalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtTempat.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            txtProdi.requestFocus();
        }
    }//GEN-LAST:event_dtTanggalKeyPressed

    private void txtProdiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtProdiKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            dtTanggal.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            txtAsal.requestFocus();
        }
    }//GEN-LAST:event_txtProdiKeyPressed

    private void txtAsalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAsalKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtProdi.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            txtAlamat.requestFocus();
        }
    }//GEN-LAST:event_txtAsalKeyPressed

    private void txtAlamatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAlamatKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtAsal.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            btnClear.requestFocus();
        }
    }//GEN-LAST:event_txtAlamatKeyPressed

    private void btnClearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnClearKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtAlamat.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_btnClearKeyPressed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtAlamat.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            btnEdit.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            btnClear.requestFocus();
        }
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void btnEditKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnEditKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtAlamat.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_RIGHT){
            btnHapus.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            btnSimpan.requestFocus();
        }
    }//GEN-LAST:event_btnEditKeyPressed

    private void btnHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHapusKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            txtAlamat.requestFocus();
        }else if(evt.getKeyCode() == KeyEvent.VK_LEFT){
            btnEdit.requestFocus();
        }
    }//GEN-LAST:event_btnHapusKeyPressed

    private void tabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelKeyReleased
        if(evt.getKeyCode() == KeyEvent.VK_UP){
            tabelMouseClicked(null);
        }else if(evt.getKeyCode() == KeyEvent.VK_DOWN){
            tabelMouseClicked(null);
        }
    }//GEN-LAST:event_tabelKeyReleased

    public void loadData(){
        tb.getDataVector().removeAllElements();
        tb.fireTableDataChanged();
        
        try{
            Koneksi.koneksi();
            Statement stm = con.createStatement();
            String sql = "select * from mahasiswa";
            ResultSet rs = stm.executeQuery(sql);
            while(rs.next()){
                Object[] o = new Object[8];
                o[1] = rs.getString("NIM");
                o[2] = rs.getString("Nama");
                o[3] = rs.getString("Tempat_Lahir");
                o[4] = rs.getDate("Tanggal_Lahir");
                o[5] = rs.getString("Prodi");
                o[6] = rs.getString("Asal_Sekolah");
                o[7] = rs.getString("Alamat");
                tb.addRow(o);
            }
            noUrut();
            stm.close();
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal Load Data\n" + e.getMessage());
            //System.out.println(e.getMessage());
        }
    }
    
    public void noUrut(){
        int baris = tb.getRowCount();
        for(int i = 0; i < baris; i++){
            String no = String.valueOf(i + 1);
            tb.setValueAt(no, i, 0);
        }
    }
    
    public void isi(){
        String nim = txtNIM.getText();
        try {
            Koneksi.koneksi();
            String sql= "Select * from mahasiswa where NIM = '"+ nim +"'";
            Statement pst = con.prepareStatement(sql); 
            ResultSet rs = pst.executeQuery(sql);
            if(rs.next()){
                txtNama.setText(rs.getString("Nama"));
                txtTempat.setText(rs.getString("Tempat_Lahir"));
                dtTanggal.setDate(rs.getDate("Tanggal_Lahir"));
                txtProdi.setText(rs.getString("Prodi"));
                txtAsal.setText(rs.getString("Asal_Sekolah"));
                txtAlamat.setText(rs.getString("Alamat"));
            }
            con.close();
            pst.close();
        }catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Gagal Load Data" + ex.getMessage());
            //System.out.println(ex.getMessage());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(f_Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(f_Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(f_Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(f_Data_Mahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new f_Data_Mahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private com.toedter.calendar.JDateChooser dtTanggal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtNIM;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtProdi;
    private javax.swing.JTextField txtTempat;
    // End of variables declaration//GEN-END:variables
}